---
# tasks file for swygue.coreos-virt-install-iso#!/usr/bin/env ansible-playbook
- name: include podman webserver checks
  include: stop_podman_webserver.yml

- name: ensure required directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ admin_user }}"
  with_items:
    - "{{ coreos_iso_extract_dir }}"
    - "{{ ignition_files_dir }}"

- name: download required files from openshift mirror
  get_url:
    url: "{{ openshift_mirror }}/{{ item }}"
    dest: "{{ downloaded_files_dir }}/{{ item }}"
  with_items:
    - "{{ coreos_installer_kernel }}"
    - "{{ coreos_installer_initramfs }}"
    - "{{ coreos_metal_bios }}"   

- name: copy over ignition files to webserver pub directory
  copy:
    src: "{{ ignition_files_dir }}/{{ item }}.ign"
    dest: "{{ downloaded_files_dir }}/{{ item }}.ign"
  with_items:
    - master
    - worker
    - bootstrap

- name: copy over kernel to install directory 
  copy:
    src: "{{ downloaded_files_dir }}/{{ coreos_installer_kernel }}"
    dest: "{{ coreos_iso_extract_dir }}/vmlinuz"

- name: copy over kernel to install directory 
  copy:
    src: "{{ downloaded_files_dir }}/{{ coreos_installer_initramfs }}"
    dest: "{{ coreos_iso_extract_dir }}/initramfs.img"

- name: copy treeinfo to /tmp/coreos
  copy:
    src: files/treeinfo
    dest: "{{ coreos_iso_extract_dir }}/.treeinfo"

- name: include podman start/deploy tasks
  include: start_podman_webserver.yml
